# ------------------------------------------------------------------------------------------------------------ #
# Mandatorty variables - DO NOT LEAVE ANYTHING BLANK #
# Azure storage account credentials - Note if you are using a single account, you can set the same key for the belows
sunbird_private_storage_account_key: "o7g+ko5PQEg8Z1qWpsTnP6vLRYSy6x6fHX0WDeW0bhDcoAzjkD2ZMw5CZHQQxSP9xUDUzy+zB53N+AStUfzIqg=="
sunbird_public_storage_account_key: "o7g+ko5PQEg8Z1qWpsTnP6vLRYSy6x6fHX0WDeW0bhDcoAzjkD2ZMw5CZHQQxSP9xUDUzy+zB53N+AStUfzIqg=="
sunbird_management_storage_account_key: "o7g+ko5PQEg8Z1qWpsTnP6vLRYSy6x6fHX0WDeW0bhDcoAzjkD2ZMw5CZHQQxSP9xUDUzy+zB53N+AStUfzIqg=="
sunbird_artifact_storage_account_key: "o7g+ko5PQEg8Z1qWpsTnP6vLRYSy6x6fHX0WDeW0bhDcoAzjkD2ZMw5CZHQQxSP9xUDUzy+zB53N+AStUfzIqg=="
sunbird_artifact_storage_account_sas: "?sv=2021-06-08&ss=bfqt&srt=sco&sp=rwdlacupiyx&se=2023-10-31T20:07:01Z&st=2022-08-29T12:07:01Z&spr=https&sig=tforoFC6YbuOVFPF9v0kBtK7UyDbndXOivGUdWm325s%3D"

core_vault_docker_registry_url: "https://index.docker.io/v1"                 # for docker hub use https://index.docker.io/v1
core_vault_docker_registry_user: "vayu068"
core_vault_docker_registry_password: "Bel@12345"

# ------------------------------------------------------------------------------------------------------------ #
# Optional variables - Can be left blank if you dont plan to use the intended features
lp_vault_youtube_api_key:                       # youtube api token if you want to upload youtube video urls on your site

# ------------------------------------------------------------------------------------------------------------ #
# Sensible defaults which you need not change - But if you would like to change, you are free to do so
lp_vault_graph_passport_key: "long-secret-to-calm-entropy-gods"
